services:
  nbs-llm:
    image: ghcr.io/wri-indonesia/nbs-llm:latest
    container_name: nbs-llm
    restart: always
    env_file: 
      - .env.production
    expose:
      - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
